### ISSUE TITLE
Docker error (IndexError: list index out of range)

### ISSUE THREAD

**Issue by CarlosLopezES** [jiwidi/DailyQwertee#9]
Hi,

I'm trying to deploy it but I've an error:

`docker run -v /token.txt:/bot/token.txt qwerteebot
Traceback (most recent call last):
  File "/bot/qwertee_bot.py", line 39, in <module>
    url, filenames = getImages()
  File "/bot/qwertee_bot.py", line 28, in getImages
    url = getDATAfromString(r.text[ind : ind + 1000])
  File "/bot/qwertee_bot.py", line 12, in getDATAfromString
    .rsplit('data-name="')[1]
IndexError: list index out of range
`
Thanks!

**Comment by jiwidi** [comment]
Hi! 

So turns out the script on the docker folder was outdated so it wasnt scrapping correctly. 

I fixed that but it also needed some changes to the dockerfile itself. I think it should work now but i have a bug running it under my m1 (arm) laptop as it requires x64. Could you try again from the latest commit?

**Comment by CarlosLopezES** [comment]
> Hi!
> 
> So turns out the script on the docker folder was outdated so it wasnt scrapping correctly.
> 
> I fixed that but it also needed some changes to the dockerfile itself. I think it should work now but i have a bug running it under my m1 (arm) laptop as it requires x64. Could you try again from the latest commit?

Now it's working and also your bot it's working again, thanks a lot!
